#INFO
site_name: Walker_V's Notebook
site_url: https://VictorWang712.github.io/Note/
site_author: Walker_V
site_description: Walker_V's Notebook
repo_url: https://github.com/VictorWang712/Note/
repo_name: VictorWang712/Note
copyright: Copyright &copy; 2024 Walker_V

#UI
theme:
  name: material
  language: zh
  font: 
    text: LXGW WenKai Screen
    code: CodeNewRoman Nerd Font Mono
  icon: material/book/outline
  # custom_dir: docs/overrides
  
  favicon: https://i.loli.net/2021/08/05/md4l2rqvsWUaEG9.png

  